# Do something with the `multilingual_mobile_app_review_2025` dataset on Kaggle.


Kaggle's link: [multilingual-mobile-app-reviews-dataset-2025/](https://www.kaggle.com/datasets/pratyushpuri/multilingual-mobile-app-reviews-dataset-2025/code)

!pip install -q pandas numpy matplotlib seaborn

In [12]:
import os
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ROOT_DIR = Path("../").resolve()
DATA_DIR = ROOT_DIR / "data"

## EDA

In this section, we will explore what we have in this dataset. If there are anything interesting more than just detecting languages, we can try to execute it. For instance, adding a sentiment and a translation, we can guess an user's age or guessing which is his/her device_type.

In [8]:
df = pd.read_csv(str(DATA_DIR / "multilingual_mobile_app_reviews_2025.csv"))
df.head()

   review_id  user_id  ...        user_gender  app_version
0          1  1967825  ...             Female          1.4
1          2  9242600  ...               Male          8.9
2          3  7636477  ...               Male  2.8.37.5926
3          4   209031  ...             Female         10.2
4          5  7190293  ...  Prefer not to say          4.7

[5 rows x 15 columns]

In [9]:
df.describe()

         review_id       user_id       rating  num_helpful_votes     user_age
count  2514.000000  2.514000e+03  2477.000000        2514.000000  2514.000000
mean   1257.500000  5.080737e+06     3.021034         616.704057    44.247812
std     725.873612  2.846939e+06     1.149955         363.745326    18.372290
min       1.000000  1.005990e+05     1.000000           0.000000    13.000000
25%     629.250000  2.595184e+06     2.100000         287.250000    28.000000
50%    1257.500000  5.059846e+06     3.000000         620.000000    44.000000
75%    1885.750000  7.571874e+06     4.000000         920.750000    60.000000
max    2514.000000  9.995027e+06     5.000000        1249.000000    75.000000